Traceback (most recent call last):
  File "/home/maaz/Documents/Automation  with Python/python_interect_os/module_11_redirect_stream/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
